kind: ConfigMap
apiVersion: v1
metadata:
  name: qbittorrent-reaper
data:
  QBITTORRENT_HOST: {{ .Values.qbittorrentHost | quote }}
  QBITTORRENT_PORT: {{ .Values.qbittorrentPort | quote }}
  QBITTORRENT_PROTOCOL: {{ .Values.qbittorrentProtocol | quote }}
  MAX_TORRENT_AGE: {{ .Values.maxTorrentAge | quote }}
  {{ if .Values.deleteFiles }}
  DELETE_FILES: "1"
  {{ end }}
  {{ if .Values.dryRun }}
  DRY_RUN: "1"
  {{ end }}
