apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: qbittorrent-reaper
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version \| replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  schedule: {{ .Values.cronjob.schedule }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: qbittorrent-reaper
            image: mattbun/qbittorrent-reaper
            imagePullPolicy: IfNotPresent
            envFrom:
              - configMapRef:
                  name: qbittorrent-reaper
              - secretRef:
                  name: qbittorrent-reaper
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
