apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: qbittorrent-reaper
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  schedule: {{ .Values.schedule }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: qbittorrent-reaper
            image: mattbun/qbittorrent-reaper:{{ .Values.imageTag }}
            imagePullPolicy: {{ .Values.imagePullPolicy }}
            envFrom:
              - configMapRef:
                  name: qbittorrent-reaper
              - secretRef:
                  name: qbittorrent-reaper
          restartPolicy: {{ .Values.restartPolicy }}
