schedule: "0 0 * * *" # daily at midnight
maxTorrentAge: 2w
dryRun: false
deleteFiles: false

qbittorrentHost:
qbittorrentPort: 8080
qbittorrentProtocol: http
qbittorrentUsername:
qbittorrentPassword:

concurrencyPolicy: Replace
restartPolicy: OnFailure
